/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RescisoesRouteImport } from './routes/rescisoes'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdmissaoRouteImport } from './routes/admissao'
import { Route as ApiPublicEditalTipoNumeroRouteImport } from './routes/api/public/edital.$tipo.$numero'

const RescisoesRoute = RescisoesRouteImport.update({
  id: '/rescisoes',
  path: '/rescisoes',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissaoRoute = AdmissaoRouteImport.update({
  id: '/admissao',
  path: '/admissao',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEditalTipoNumeroRoute =
  ApiPublicEditalTipoNumeroRouteImport.update({
    id: '/api/public/edital/$tipo/$numero',
    path: '/api/public/edital/$tipo/$numero',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/admissao': typeof AdmissaoRoute
  '/dashboard': typeof DashboardRoute
  '/rescisoes': typeof RescisoesRoute
  '/api/public/edital/$tipo/$numero': typeof ApiPublicEditalTipoNumeroRoute
}
export interface FileRoutesByTo {
  '/admissao': typeof AdmissaoRoute
  '/dashboard': typeof DashboardRoute
  '/rescisoes': typeof RescisoesRoute
  '/api/public/edital/$tipo/$numero': typeof ApiPublicEditalTipoNumeroRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/admissao': typeof AdmissaoRoute
  '/dashboard': typeof DashboardRoute
  '/rescisoes': typeof RescisoesRoute
  '/api/public/edital/$tipo/$numero': typeof ApiPublicEditalTipoNumeroRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admissao'
    | '/dashboard'
    | '/rescisoes'
    | '/api/public/edital/$tipo/$numero'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admissao'
    | '/dashboard'
    | '/rescisoes'
    | '/api/public/edital/$tipo/$numero'
  id:
    | '__root__'
    | '/admissao'
    | '/dashboard'
    | '/rescisoes'
    | '/api/public/edital/$tipo/$numero'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdmissaoRoute: typeof AdmissaoRoute
  DashboardRoute: typeof DashboardRoute
  RescisoesRoute: typeof RescisoesRoute
  ApiPublicEditalTipoNumeroRoute: typeof ApiPublicEditalTipoNumeroRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rescisoes': {
      id: '/rescisoes'
      path: '/rescisoes'
      fullPath: '/rescisoes'
      preLoaderRoute: typeof RescisoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissao': {
      id: '/admissao'
      path: '/admissao'
      fullPath: '/admissao'
      preLoaderRoute: typeof AdmissaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/edital/$tipo/$numero': {
      id: '/api/public/edital/$tipo/$numero'
      path: '/api/public/edital/$tipo/$numero'
      fullPath: '/api/public/edital/$tipo/$numero'
      preLoaderRoute: typeof ApiPublicEditalTipoNumeroRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AdmissaoRoute: AdmissaoRoute,
  DashboardRoute: DashboardRoute,
  RescisoesRoute: RescisoesRoute,
  ApiPublicEditalTipoNumeroRoute: ApiPublicEditalTipoNumeroRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
